### ISSUE TITLE
Project migration

### ISSUE THREAD

**Issue by foxx** [synca/aio.testing#6]
Hey,

I can see that the project has been migrated from [phlax](https://github.com/phlax/aio.testing), however because it's a fork rather than a project transfer. This means all the issues haven't followed over and the project is not redirecting to the new place.

May I request that the new repo is closed and the old one transferred over in its place?

**Comment by phlax** [comment]
hi,

i did actually move the project and the issues are now on here, just that they are closed:

https://github.com/synca/aio.testing/issues?q=is%3Aissue+is%3Aclosed

**Comment by foxx** [comment]
Ah damn, I'm not sure how I missed this... I must have had a brain fail, sorry for the wasted time!
